import React from "react";
import {
  Activity,
  AlertTriangle,
  BarChart3,
  CalendarClock,
  Camera,
  CameraOff,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock3,
  CircleDot,
  Crosshair,
  Database,
  Download,
  Eye,
  EyeOff,
  FileDown,
  FileSpreadsheet,
  FileText,
  Gauge,
  History,
  ImageOff,
  ImageUp,
  Info,
  Layers3,
  ListChecks,
  Lock,
  MapPin,
  MapPinned,
  Minus,
  Monitor,
  Navigation,
  Plus,
  RadioTower,
  Redo2,
  Route,
  Save,
  ScanLine,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  SquarePen,
  Trash2,
  Undo2,
  Unlock,
  Upload,
  Video,
  Waypoints,
  X,
  XCircle,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  alert: AlertTriangle,
  analytics: BarChart3,
  "calendar-clock": CalendarClock,
  camera: Camera,
  "camera-off": CameraOff,
  car: Car,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  clock: Clock3,
  "circle-dot": CircleDot,
  close: X,
  database: Database,
  download: Download,
  edit: SquarePen,
  excel: FileSpreadsheet,
  eye: Eye,
  "eye-off": EyeOff,
  file: FileText,
  "file-down": FileDown,
  gauge: Gauge,
  history: History,
  image: ImageUp,
  "image-off": ImageOff,
  info: Info,
  lanes: Layers3,
  "list-checks": ListChecks,
  lock: Lock,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  minus: Minus,
  monitor: Monitor,
  navigation: Navigation,
  plus: Plus,
  "radio-tower": RadioTower,
  redo: Redo2,
  route: Route,
  save: Save,
  "scan-line": ScanLine,
  settings: Settings2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  target: Crosshair,
  trash: Trash2,
  undo: Undo2,
  unlock: Unlock,
  upload: Upload,
  video: Video,
  waypoints: Waypoints,
  x: X,
  "x-circle": XCircle,
};

export default function AppIcon({ name, size = 16, strokeWidth = 2, className = "", ...props }) {
  const IconComponent = ICONS[name] || Info;
  const classNames = ["app-icon", className].filter(Boolean).join(" ");

  return <IconComponent className={classNames} size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
